<a href="https://colab.research.google.com/github/alexxpz/TensorFlowMastery/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Covering fundamental concepts of tensors using TensorFlow

More specifically we're going to cover:
* Intorduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors and NumPy
* Using @tf.function (a way to speed up regular Python functions)
* Using GPUs with TensorFlow (or TPUs)
* Exercises

## Introduction to Tensors

In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.18.0


In [2]:
# Creating tensors with tf.constant()
scalar =  tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Checking the number of dimensions of a tensor (ndim)
scalar.ndim

0

In [4]:
# Creating a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# Checking the dimension of the vector
vector.ndim

1

In [6]:
# Creating a matrix and checking ndim
matrix = tf.constant([[10,7],[7,10]]) #list of list
matrix.ndim

2

In [7]:
# Creating another matrix
another_matrix = tf.constant([[10.,7.],[7.,10.],[5.,5.]], dtype=tf.float16) # Datatype parameter is used to use more or less storage for the data (higher the number, higher the precision and storage space). DEFAULT IS INT32.
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 5.,  5.]], dtype=float16)>

In [8]:
# Checking ndim of another_matrix
another_matrix.ndim

2

In [9]:
# Creating a tensor instead
tensor = tf.constant([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]] , [[13,14,15], [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [10]:
tensor.ndim

3

What we've created so far:
* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers

### Creating tensors with tf.Variable

In [11]:
# Creating the same tensor as before with tf.Variable()

changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [12]:
# Changing one of the elements in the changeable tensor
# changeable_tensor[0] = 7 Doesn't work we need to use assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [13]:
# Now changing one element in the unchangeable tensor
# unchangeable_tensor[0].assign(7) : Doesn't work because a constant tensor can't be modified
unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

🔑 **Note:** Rarely in practice will you need to decide between Variable and Constant tensors as TensorFlow does this automatically when building Neural Networks. In doubt, always use Constant and change it to Variable later if needed.

### Creating random tensors


In [14]:
# Creating two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

# Checking if they're equal :
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffling the order of elements in a tensor

It's sometimes important to feed NN with randomly shuffled inputs (for image recognition for example), but not necessarily for LLMs or other models where input order matters.

In [15]:
not_shuffled = tf.constant([[10,7], [3,4], [2,5]])

# Shuffling :
tf.random.shuffle(not_shuffled, seed = 42) # Seed doesn't seem to set a specific shuffle result

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [16]:
tf.random.set_seed(42) # This ensures that subsequent randomness in tensors manipulation will be consistent and reproducible
tf.random.shuffle(not_shuffled, seed = 42) # Will now always give the same shuffled result

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

### Creating tensors using tf.ones and tf.zeros

In [17]:
# Creating a tensor of all 1s
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [18]:
# Creating a tensor of all 0s
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turning NumPy arrays into tensors

The main difference between NumPy arrays and TensorFlow tensors is that tensors can be ran on a GPU much faster.

In [19]:
import numpy as np
numpy_A = np.arange(1, 25, dtype = np.int32) # Create a NumPy array between 1 and 25 (arange : array range)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [20]:
A = tf.constant(numpy_A, shape=(2,3,4)) # Create a tensor from a NumPy array 2 objetcs of shape (3, 4) = 2 matrices of 3 rows and 4 columns using numpy_A elements
B = tf.constant(numpy_A) # Creating a tf vector from numpy_A (1 dimension)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [21]:
A.ndim

3

### Getting information from tensors

*   Shape
*   Rank
*   Axis or dimension
*   Size (tensor[0], tensor[ :, 1], ..)



In [22]:
# Create a rank 4 tensor (4 dimensions)

rank_4_tensor = tf.zeros(shape=(2,3,4,5))
rank_4_tensor
# It is a tensor composed of 2 lists of 3 matrices with 4 rows and 5 columns

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [23]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)
# Size is numpy=120 because the shape is 2*3*4*5 = 120

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [24]:
# Getting various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1]) # Last item
print("Total number of elements in our tensor:", tf.size(rank_4_tensor))
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor: 120


### Indexing tensors

Tensors can be indexed just like Pythjoin lists.

In [25]:
# Getting the first 2 elemnts of each dimension

rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [26]:
# Getting the first element from each dimension from each index except for the final one
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [27]:
# Creating a rank 2 tensor (2 dim)
rank_2_tensor = tf.constant([[1,2],[3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [28]:
# Getting the last item of each row of our rank 2
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [29]:
# Adding extra dimension to the rank 2 tensor
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [30]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # -1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

### Manipulating tensors (tensor operations)

**Basic operations**

`+`,`-`,`*`,`/`

In [31]:
# Adding or substracting values to a tensor using the addition operator
tensor = tf.constant([[10,7],[3,4]])
tensor + 10
tensor - 10
# Original tensor is unchanged (we didn't do tensor = tensor + 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [32]:
# Multiplying or dividing values of a tensor
tensor * 10
tensor / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

In [33]:
# Can use the TensorFlow built-in function as well
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

**Matrix multiplication**

In machine learning, matrix multiplication is one of the most common tensor operations.

Rules for Matrix Multiplication:
1. Inner dimensions must match i.e : AxB can be multiplied by BxC matrices (C can equal A)
2. The resulting matrix has the shape of the outer dimensions (AxC here)

In [34]:
# Matrix multiplication in TensorFlow

tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [35]:
# Matrix multiplication with Python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [36]:
# Creating 2 tensors of shape (3, 2)

X = tf.constant([[1,2],[3,4],[5,6]])
Y = tf.constant([[7,8],[9,10],[11,12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [37]:
# Matmul or @ operator doesn't work because 3x2 matrices can't be multiplied by 3x2 matrices
# But we can reshape Y by going from a 3x2 to a 2x3 matrix using tf.reshape

tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [38]:
tf.reshape(Y, shape=(2,3)) # Keeps the same order of elements in the tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [39]:
# Can do the shape manipulation with transpose however the transposed matrix is different than the reshaped matrix
Y, tf.transpose(Y), tf.reshape(Y, shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  9, 11],
        [ 8, 10, 12]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]], dtype=int32)>)

In [40]:
# Trying matrix multiplication with transpose instead of reshape
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

**The dot product**

Matrix multiplication is also called dot product.
You can perform matrix multiplication using:
* `@`
* `tf.matmul`
* `tf.tensordot()`

In [41]:
# Performing the dot product on X and Y (requires X to be transposed or reshaped)
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [42]:
# Performing the dot product on Y and X (requires Y to be transposed or reshaped)
tf.tensordot(tf.transpose(Y), X, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89, 116],
       [ 98, 128]], dtype=int32)>

In [43]:
# Performing X.Y with Y transposed
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [44]:
# Performing X.Y with Y reshaped
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [45]:
# Checking the values of Y, reshaped Y and transposed Y
print("Normal Y:")
print(Y, "\n") # New line

print("Y reshaped:")
print(tf.reshape(Y, shape=(2,3)), "\n")

print("Y transposed:")
print(tf.transpose(Y), "\n")


Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped:
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32) 



### Changing the datatype of a tensor

In [46]:
# Creating a new tensor with default datatype (float32)

B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [47]:
# Creating a new tensor with int datatype (int32)

C = tf.constant([7, 10])
C.dtype

tf.int32

In [48]:
# Changing from float32 to float16 (mixed precision for lower memory usage and faster computing on hardware)

D = tf.cast(B, dtype=tf.float16)
B, D

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>)

In [49]:
# Changing from int32 to float32
E = tf.cast(C, dtype=tf.float32)
F = tf.cast(C, dtype=tf.float16)
C, E, F

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>)

### Aggregating tensors

Aggregating tensors = condensing them from multiple values to a smaller amount of values (basically aggregating elements; duh). Here are some forms of aggregation:

* Absolute values
* Min
* Max
* Sum
* Mean

In [50]:
# Initiating a random larger tensors with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0,100, size = 50))
E, tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(50,), dtype=int64, numpy=
 array([17,  6,  3, 53,  9, 60, 31, 41, 18, 57, 23, 32, 96, 16, 46,  9, 47,
        55, 94,  5, 50, 29, 27, 61, 95,  5, 19, 69, 24, 63, 11, 70, 83, 19,
        52, 49, 47, 34, 90, 90, 24, 42, 48, 77, 98, 69, 58, 45, 66, 92])>,
 <tf.Tensor: shape=(), dtype=int32, numpy=50>,
 TensorShape([50]),
 1)

In [51]:
# Getting the absolute values
tf.abs(E) # Same here since all values of E are positive

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([17,  6,  3, 53,  9, 60, 31, 41, 18, 57, 23, 32, 96, 16, 46,  9, 47,
       55, 94,  5, 50, 29, 27, 61, 95,  5, 19, 69, 24, 63, 11, 70, 83, 19,
       52, 49, 47, 34, 90, 90, 24, 42, 48, 77, 98, 69, 58, 45, 66, 92])>

In [52]:
# Getting the minimum and maximum
tf.reduce_min(E), tf.reduce_max(E)

(<tf.Tensor: shape=(), dtype=int64, numpy=3>,
 <tf.Tensor: shape=(), dtype=int64, numpy=98>)

In [53]:
# Getting the mean and sum
tf.reduce_mean(E), tf.reduce_sum(E)

(<tf.Tensor: shape=(), dtype=int64, numpy=46>,
 <tf.Tensor: shape=(), dtype=int64, numpy=2324>)

In [54]:
# Also getting more statistical information out of our tensor
tf.math.reduce_std(tf.cast(E,dtype=tf.float32)), tf.math.reduce_variance(tf.cast(E,dtype=tf.float32))

(<tf.Tensor: shape=(), dtype=float32, numpy=27.904293060302734>,
 <tf.Tensor: shape=(), dtype=float32, numpy=778.6495971679688>)

### Finding the positional maximum and minimum

In [55]:
# Creating a new tensor for finding positional maximum and minimum

tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [56]:
# Finding the positional maximum

tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [57]:
# Indexing on the positional maximum
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>

In [58]:
# Finding the max value of F

tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>

In [59]:
# Checking equality of the methods

F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [60]:
# Doing the same with minimum

print("Positional minimum:", tf.argmin(F))
print("Indexing on positional minimum:", F[tf.argmin(F)])
print("Miniumum using reduce_min", tf.reduce_min(F))
print("Checking equality of methods", F[tf.argmin(F)] == tf.reduce_min(F))

Positional minimum: tf.Tensor(16, shape=(), dtype=int64)
Indexing on positional minimum: tf.Tensor(0.009463668, shape=(), dtype=float32)
Miniumum using reduce_min tf.Tensor(0.009463668, shape=(), dtype=float32)
Checking equality of methods tf.Tensor(True, shape=(), dtype=bool)


### Squeezing a tensor (removing all single dimensions)

In [61]:
# Creating a tensor with single dimensions

tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G, G.shape

(<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
 array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
            0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
            0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
            0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
            0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
            0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
            0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
            0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
            0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
            0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
       dtype=float32)>,
 TensorShape([1, 1, 1, 1, 50]))

In [62]:
# Removing single dimensions from G using the squeeze method

G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

### One-hot encoding tensors

One-hot encoding is a form of numerical encoding. It it great for classification usages and helping Neural Network ingest data with classes

In [63]:
# Creating a list of indices

some_list = [0,1,2,3] # Could be red, green, blue, purple

# On-hot encoding the list of indices
tf.one_hot(some_list, depth = len(some_list))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [64]:
# Specifying custom values for one-hot encoding
tf.one_hot(some_list, depth=len(some_list), on_value="ON",off_value="OFF")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'ON', b'OFF', b'OFF', b'OFF'],
       [b'OFF', b'ON', b'OFF', b'OFF'],
       [b'OFF', b'OFF', b'ON', b'OFF'],
       [b'OFF', b'OFF', b'OFF', b'ON']], dtype=object)>

### Other mathematical operations on tensors

Squaring, log, square root

In [65]:
# Creating a tensor using tf.range

H = tf.range(1,11) # Ranges tensor values from A to B-1 (length is B-A)
H

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)>

In [66]:
# Squaring it
tf.square(H)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)>

In [67]:
# Square-rooting it
tf.sqrt(tf.cast(H, dtype=tf.float16)) # Requires to cast change the dtype to float16 or float32

<tf.Tensor: shape=(10,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ,
       3.162], dtype=float16)>

In [68]:
# Logging it
tf.math.log(tf.cast(H, dtype=tf.float16)) # Requires to cast change the dtype to float16 or float32

<tf.Tensor: shape=(10,), dtype=float16, numpy=
array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 , 2.303 ], dtype=float16)>

### Tensors and NumPy

TensorFlow interacts well with NumPy arrays.
The main difference is that a Tensor will run faster on GPU or TPU.

In [69]:
# Creating a tensor directly from a NumPy array

J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [70]:
# Converting back to a NumPy array

np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [71]:
# Converting to a NumPy array using .numpy() method

J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [72]:
# Defautl types of each are slightly different

numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])

# Checking datatype of each
numpy_J.dtype, tensor_J.dtype # NumPy is float64 by default while TensorFlow is float32 by default

(tf.float64, tf.float32)

### Finding access to GPUs

In [73]:
# Listing physical devices available to TensorFlow

tf.config.list_physical_devices() # Running on a CPU by default

# You can go into Runtime > Change Runtime Type and select a GPU that is available.

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [74]:
!nvidia-smi # Check the type of GPU used

Wed Feb 19 21:48:57 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   44C    P0             27W /   70W |     106MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

If you have access to CUDA-enabled GPU, TensorFlow will automatically use it whenever possible.